---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SiteConfig:
  extensions:
    - SocialstreamSiteConfig
  available_services:
    - dailymotion
    - facebook_page
    - flickr
    - github
    - rss
    - twitter
    - vimeo
    - youtube
    - twitter_hashtag
SocialstreamController:
  enable_cache: true
Director:
  rules:
    'socialstream//$Action/$ID/$Name': 'SocialstreamController'